if(EXISTS "/home/ti/Dbc/CANdb-master/tests/dbcparser_tests[1]_tests.cmake")
  include("/home/ti/Dbc/CANdb-master/tests/dbcparser_tests[1]_tests.cmake")
else()
  add_test(dbcparser_tests_NOT_BUILT dbcparser_tests_NOT_BUILT)
endif()
