if(EXISTS "/home/ti/Dbc/CANdb-master/tests/prop_tests[1]_tests.cmake")
  include("/home/ti/Dbc/CANdb-master/tests/prop_tests[1]_tests.cmake")
else()
  add_test(prop_tests_NOT_BUILT prop_tests_NOT_BUILT)
endif()
