if(EXISTS "/home/ti/Dbc/CANdb-master/tests/stringutils_tests[1]_tests.cmake")
  include("/home/ti/Dbc/CANdb-master/tests/stringutils_tests[1]_tests.cmake")
else()
  add_test(stringutils_tests_NOT_BUILT stringutils_tests_NOT_BUILT)
endif()
